name: "Prepare Python environment"
description: "Set up Python and install dependencies"
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.14
    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt
